//
// This file was generated by Catalyst's Unreal compiler at 26/04/2025 13:38:43.
// It is recommended not to modify this file. Modify the source spec file instead.
//

#pragma once

#include "Misc/DateTime.h"

#include "CatalystExampleUsers.generated.h"

USTRUCT(BlueprintType)
struct FCatalystExampleQueryUsersRequest
{
    GENERATED_BODY()


    static TArray<uint8> ToBytes(const FCatalystExampleQueryUsersRequest& Object);

    TArray<uint8> ToBytes() const;

    static TOptional<FCatalystExampleQueryUsersRequest> FromBytes(const TArray<uint8>& Bytes);
};

USTRUCT(BlueprintType)
struct FCatalystExampleQueryUsersResponse
{
    GENERATED_BODY()

    UPROPERTY(EditAnywhere)
    TArray<FString> UserIds;

    static TArray<uint8> ToBytes(const FCatalystExampleQueryUsersResponse& Object);

    TArray<uint8> ToBytes() const;

    static TOptional<FCatalystExampleQueryUsersResponse> FromBytes(const TArray<uint8>& Bytes);
};

USTRUCT(BlueprintType)
struct FCatalystExampleGetUserRequest
{
    GENERATED_BODY()

    UPROPERTY(EditAnywhere)
    FString UserId;

    static TArray<uint8> ToBytes(const FCatalystExampleGetUserRequest& Object);

    TArray<uint8> ToBytes() const;

    static TOptional<FCatalystExampleGetUserRequest> FromBytes(const TArray<uint8>& Bytes);
};

USTRUCT(BlueprintType)
struct FCatalystExampleGetUserResponse
{
    GENERATED_BODY()

    UPROPERTY(EditAnywhere)
    FString Id;

    UPROPERTY(EditAnywhere)
    FString DisplayName;

    UPROPERTY(EditAnywhere)
    TArray<FString> Roles;

    UPROPERTY(EditAnywhere)
    FDateTime TimeCreated;

    UPROPERTY(EditAnywhere)
    FDateTime TimeLastLoggedIn;

    static TArray<uint8> ToBytes(const FCatalystExampleGetUserResponse& Object);

    TArray<uint8> ToBytes() const;

    static TOptional<FCatalystExampleGetUserResponse> FromBytes(const TArray<uint8>& Bytes);
};

USTRUCT(BlueprintType)
struct FCatalystExampleUserEvent
{
    GENERATED_BODY()

    UPROPERTY(EditAnywhere)
    FString UserId;

    static TArray<uint8> ToBytes(const FCatalystExampleUserEvent& Object);

    TArray<uint8> ToBytes() const;

    static TOptional<FCatalystExampleUserEvent> FromBytes(const TArray<uint8>& Bytes);
};

