//
// This file was generated by Catalyst's Unreal compiler at 26/04/2025 13:38:43.
// It is recommended not to modify this file. Modify the source spec file instead.
//

#pragma once

#include "CatalystExampleRoles.generated.h"

USTRUCT(BlueprintType)
struct FCatalystExampleQueryRolesRequest
{
    GENERATED_BODY()


    static TArray<uint8> ToBytes(const FCatalystExampleQueryRolesRequest& Object);

    TArray<uint8> ToBytes() const;

    static TOptional<FCatalystExampleQueryRolesRequest> FromBytes(const TArray<uint8>& Bytes);
};

USTRUCT(BlueprintType)
struct FCatalystExampleQueryRolesResponse
{
    GENERATED_BODY()

    UPROPERTY(EditAnywhere)
    TArray<FString> RoleIds;

    static TArray<uint8> ToBytes(const FCatalystExampleQueryRolesResponse& Object);

    TArray<uint8> ToBytes() const;

    static TOptional<FCatalystExampleQueryRolesResponse> FromBytes(const TArray<uint8>& Bytes);
};

USTRUCT(BlueprintType)
struct FCatalystExampleGetRolesRequest
{
    GENERATED_BODY()

    UPROPERTY(EditAnywhere)
    TArray<FString> RoleIds;

    static TArray<uint8> ToBytes(const FCatalystExampleGetRolesRequest& Object);

    TArray<uint8> ToBytes() const;

    static TOptional<FCatalystExampleGetRolesRequest> FromBytes(const TArray<uint8>& Bytes);
};

USTRUCT(BlueprintType)
struct FCatalystExampleGetRoleResponse
{
    GENERATED_BODY()

    UPROPERTY(EditAnywhere)
    FString Id;

    UPROPERTY(EditAnywhere)
    FString RoleName;

    UPROPERTY(EditAnywhere)
    TArray<FString> Permissions;

    static TArray<uint8> ToBytes(const FCatalystExampleGetRoleResponse& Object);

    TArray<uint8> ToBytes() const;

    static TOptional<FCatalystExampleGetRoleResponse> FromBytes(const TArray<uint8>& Bytes);
};

USTRUCT(BlueprintType)
struct FCatalystExampleGetRolesResponse
{
    GENERATED_BODY()

    UPROPERTY(EditAnywhere)
    TArray<FCatalystExampleGetRoleResponse> Roles;

    static TArray<uint8> ToBytes(const FCatalystExampleGetRolesResponse& Object);

    TArray<uint8> ToBytes() const;

    static TOptional<FCatalystExampleGetRolesResponse> FromBytes(const TArray<uint8>& Bytes);
};

USTRUCT(BlueprintType)
struct FCatalystExampleCreateRoleRequest
{
    GENERATED_BODY()

    UPROPERTY(EditAnywhere)
    FString Id;

    UPROPERTY(EditAnywhere)
    FString RoleName;

    UPROPERTY(EditAnywhere)
    TArray<FString> Permissions;

    static TArray<uint8> ToBytes(const FCatalystExampleCreateRoleRequest& Object);

    TArray<uint8> ToBytes() const;

    static TOptional<FCatalystExampleCreateRoleRequest> FromBytes(const TArray<uint8>& Bytes);
};

USTRUCT(BlueprintType)
struct FCatalystExampleRoleEvent
{
    GENERATED_BODY()

    UPROPERTY(EditAnywhere)
    TArray<FString> RoleIds;

    static TArray<uint8> ToBytes(const FCatalystExampleRoleEvent& Object);

    TArray<uint8> ToBytes() const;

    static TOptional<FCatalystExampleRoleEvent> FromBytes(const TArray<uint8>& Bytes);
};

