# Makefile generated by MakefileGenerator.cs
# *DO NOT EDIT*

UNREALROOTPATH = /media/liam/LiamT7/Unreal Engine/5.4
GAMEPROJECTFILE =/media/liam/LiamT7/Lactose/Client/LactoseGame/LactoseGame.uproject

TARGETS = \
	LactoseGame-Linux-DebugGame  \
	LactoseGame-Linux-Shipping  \
	LactoseGame \
	LactoseGameEditor-Linux-DebugGame  \
	LactoseGameEditor-Linux-Shipping  \
	LactoseGameEditor \
	UnrealEditor-Linux-DebugGame  \
	UnrealEditor-Linux-Shipping  \
	UnrealEditor \
	UnrealGame-Linux-DebugGame  \
	UnrealGame-Linux-Shipping  \
	UnrealGame\
	configure

BUILD = bash "$(UNREALROOTPATH)/Engine/Build/BatchFiles/Linux/Build.sh"
PROJECTBUILD = "$(UNREALROOTPATH)/Engine/Binaries/ThirdParty/DotNet/6.0.302/linux/dotnet" "$(UNREALROOTPATH)/Engine/Binaries/DotNET/UnrealBuildTool/UnrealBuildTool.dll"

all: StandardSet

RequiredTools: CrashReportClient-Linux-Shipping CrashReportClientEditor-Linux-Shipping ShaderCompileWorker UnrealLightmass EpicWebHelper-Linux-Shipping

StandardSet: RequiredTools UnrealFrontend LactoseGameEditor UnrealInsights

DebugSet: RequiredTools UnrealFrontend-Linux-Debug LactoseGameEditor-Linux-Debug


LactoseGame-Linux-DebugGame:
	 $(PROJECTBUILD) LactoseGame Linux DebugGame  -project="$(GAMEPROJECTFILE)" $(ARGS)

LactoseGame-Linux-Shipping:
	 $(PROJECTBUILD) LactoseGame Linux Shipping  -project="$(GAMEPROJECTFILE)" $(ARGS)

LactoseGame:
	 $(PROJECTBUILD) LactoseGame Linux Development  -project="$(GAMEPROJECTFILE)" $(ARGS)

LactoseGameEditor-Linux-DebugGame:
	 $(PROJECTBUILD) LactoseGameEditor Linux DebugGame  -project="$(GAMEPROJECTFILE)" $(ARGS)

LactoseGameEditor-Linux-Shipping:
	 $(PROJECTBUILD) LactoseGameEditor Linux Shipping  -project="$(GAMEPROJECTFILE)" $(ARGS)

LactoseGameEditor:
	 $(PROJECTBUILD) LactoseGameEditor Linux Development  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealEditor-Linux-DebugGame:
	 $(BUILD) UnrealEditor Linux DebugGame  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealEditor-Linux-Shipping:
	 $(BUILD) UnrealEditor Linux Shipping  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealEditor:
	 $(BUILD) UnrealEditor Linux Development  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealGame-Linux-DebugGame:
	 $(BUILD) UnrealGame Linux DebugGame  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealGame-Linux-Shipping:
	 $(BUILD) UnrealGame Linux Shipping  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealGame:
	 $(BUILD) UnrealGame Linux Development  -project="$(GAMEPROJECTFILE)" $(ARGS)

configure:
	xbuild /property:Configuration=Development /verbosity:quiet /nologo "$(UNREALROOTPATH)/Engine/Source/Programs/UnrealBuildTool/UnrealBuildTool.csproj"
	$(PROJECTBUILD) -projectfiles -project="\"$(GAMEPROJECTFILE)\"" -game -engine 

.PHONY: $(TARGETS)
