//
// This file was generated by Catalyst's Unreal compiler at 02/05/2025 17:42:48.
// It is recommended not to modify this file. Modify the source spec file instead.
//

#pragma once

#include "Misc/DateTime.h"

#include "LactoseIdentityUsersDtosUsers.generated.h"

USTRUCT(BlueprintType)
struct FLactoseIdentityUsersDtosQueryUsersRequest
{
    GENERATED_BODY()


    static TArray<uint8> ToBytes(const FLactoseIdentityUsersDtosQueryUsersRequest& Object);

    TArray<uint8> ToBytes() const;

    static TOptional<FLactoseIdentityUsersDtosQueryUsersRequest> FromBytes(const TArray<uint8>& Bytes);
};

USTRUCT(BlueprintType)
struct FLactoseIdentityUsersDtosQueryUsersResponse
{
    GENERATED_BODY()

    UPROPERTY(EditAnywhere)
    TArray<FString> UserIds;

    static TArray<uint8> ToBytes(const FLactoseIdentityUsersDtosQueryUsersResponse& Object);

    TArray<uint8> ToBytes() const;

    static TOptional<FLactoseIdentityUsersDtosQueryUsersResponse> FromBytes(const TArray<uint8>& Bytes);
};

USTRUCT(BlueprintType)
struct FLactoseIdentityUsersDtosGetUserRequest
{
    GENERATED_BODY()

    UPROPERTY(EditAnywhere)
    FString UserId;

    static TArray<uint8> ToBytes(const FLactoseIdentityUsersDtosGetUserRequest& Object);

    TArray<uint8> ToBytes() const;

    static TOptional<FLactoseIdentityUsersDtosGetUserRequest> FromBytes(const TArray<uint8>& Bytes);
};

USTRUCT(BlueprintType)
struct FLactoseIdentityUsersDtosGetUserResponse
{
    GENERATED_BODY()

    UPROPERTY(EditAnywhere)
    FString Id;

    UPROPERTY(EditAnywhere)
    FString DisplayName;

    UPROPERTY(EditAnywhere)
    TArray<FString> Roles;

    UPROPERTY(EditAnywhere)
    FDateTime TimeCreated;

    UPROPERTY(EditAnywhere)
    FDateTime TimeLastLoggedIn;

    static TArray<uint8> ToBytes(const FLactoseIdentityUsersDtosGetUserResponse& Object);

    TArray<uint8> ToBytes() const;

    static TOptional<FLactoseIdentityUsersDtosGetUserResponse> FromBytes(const TArray<uint8>& Bytes);
};

USTRUCT(BlueprintType)
struct FLactoseIdentityUsersDtosUserEvent
{
    GENERATED_BODY()

    UPROPERTY(EditAnywhere)
    FString UserId;

    static TArray<uint8> ToBytes(const FLactoseIdentityUsersDtosUserEvent& Object);

    TArray<uint8> ToBytes() const;

    static TOptional<FLactoseIdentityUsersDtosUserEvent> FromBytes(const TArray<uint8>& Bytes);
};

