//
// This file was generated by Catalyst's Unreal compiler at 02/05/2025 17:42:48.
// It is recommended not to modify this file. Modify the source spec file instead.
//

#include "LactoseIdentityUsersDtosUsers.h"

#include "CatalystJson.h"
#include "Templates/SharedPointer.h"


TArray<uint8> FLactoseIdentityUsersDtosQueryUsersRequest::ToBytes(const FLactoseIdentityUsersDtosQueryUsersRequest& Object)
{
    TSharedPtr<FJsonObject> JsonObject = Catalyst::Json::StructToJsonObject(Object);
    return JsonObject ? Catalyst::Json::JsonObjectToBytes(JsonObject.ToSharedRef()) : TArray<uint8>();
}

TArray<uint8> FLactoseIdentityUsersDtosQueryUsersRequest::ToBytes() const
{
    return ToBytes(*this);
}

TOptional<FLactoseIdentityUsersDtosQueryUsersRequest> FLactoseIdentityUsersDtosQueryUsersRequest::FromBytes(const TArray<uint8>& Bytes)
{
    TSharedPtr<FJsonObject> JsonObject = Catalyst::Json::BytesToJsonObject(Bytes);
    return JsonObject ? Catalyst::Json::JsonObjectToStruct<FLactoseIdentityUsersDtosQueryUsersRequest>(JsonObject.ToSharedRef()) : TOptional<FLactoseIdentityUsersDtosQueryUsersRequest>();
}

TArray<uint8> FLactoseIdentityUsersDtosQueryUsersResponse::ToBytes(const FLactoseIdentityUsersDtosQueryUsersResponse& Object)
{
    TSharedPtr<FJsonObject> JsonObject = Catalyst::Json::StructToJsonObject(Object);
    return JsonObject ? Catalyst::Json::JsonObjectToBytes(JsonObject.ToSharedRef()) : TArray<uint8>();
}

TArray<uint8> FLactoseIdentityUsersDtosQueryUsersResponse::ToBytes() const
{
    return ToBytes(*this);
}

TOptional<FLactoseIdentityUsersDtosQueryUsersResponse> FLactoseIdentityUsersDtosQueryUsersResponse::FromBytes(const TArray<uint8>& Bytes)
{
    TSharedPtr<FJsonObject> JsonObject = Catalyst::Json::BytesToJsonObject(Bytes);
    return JsonObject ? Catalyst::Json::JsonObjectToStruct<FLactoseIdentityUsersDtosQueryUsersResponse>(JsonObject.ToSharedRef()) : TOptional<FLactoseIdentityUsersDtosQueryUsersResponse>();
}

TArray<uint8> FLactoseIdentityUsersDtosGetUserRequest::ToBytes(const FLactoseIdentityUsersDtosGetUserRequest& Object)
{
    TSharedPtr<FJsonObject> JsonObject = Catalyst::Json::StructToJsonObject(Object);
    return JsonObject ? Catalyst::Json::JsonObjectToBytes(JsonObject.ToSharedRef()) : TArray<uint8>();
}

TArray<uint8> FLactoseIdentityUsersDtosGetUserRequest::ToBytes() const
{
    return ToBytes(*this);
}

TOptional<FLactoseIdentityUsersDtosGetUserRequest> FLactoseIdentityUsersDtosGetUserRequest::FromBytes(const TArray<uint8>& Bytes)
{
    TSharedPtr<FJsonObject> JsonObject = Catalyst::Json::BytesToJsonObject(Bytes);
    return JsonObject ? Catalyst::Json::JsonObjectToStruct<FLactoseIdentityUsersDtosGetUserRequest>(JsonObject.ToSharedRef()) : TOptional<FLactoseIdentityUsersDtosGetUserRequest>();
}

TArray<uint8> FLactoseIdentityUsersDtosGetUserResponse::ToBytes(const FLactoseIdentityUsersDtosGetUserResponse& Object)
{
    TSharedPtr<FJsonObject> JsonObject = Catalyst::Json::StructToJsonObject(Object);
    return JsonObject ? Catalyst::Json::JsonObjectToBytes(JsonObject.ToSharedRef()) : TArray<uint8>();
}

TArray<uint8> FLactoseIdentityUsersDtosGetUserResponse::ToBytes() const
{
    return ToBytes(*this);
}

TOptional<FLactoseIdentityUsersDtosGetUserResponse> FLactoseIdentityUsersDtosGetUserResponse::FromBytes(const TArray<uint8>& Bytes)
{
    TSharedPtr<FJsonObject> JsonObject = Catalyst::Json::BytesToJsonObject(Bytes);
    return JsonObject ? Catalyst::Json::JsonObjectToStruct<FLactoseIdentityUsersDtosGetUserResponse>(JsonObject.ToSharedRef()) : TOptional<FLactoseIdentityUsersDtosGetUserResponse>();
}

TArray<uint8> FLactoseIdentityUsersDtosUserEvent::ToBytes(const FLactoseIdentityUsersDtosUserEvent& Object)
{
    TSharedPtr<FJsonObject> JsonObject = Catalyst::Json::StructToJsonObject(Object);
    return JsonObject ? Catalyst::Json::JsonObjectToBytes(JsonObject.ToSharedRef()) : TArray<uint8>();
}

TArray<uint8> FLactoseIdentityUsersDtosUserEvent::ToBytes() const
{
    return ToBytes(*this);
}

TOptional<FLactoseIdentityUsersDtosUserEvent> FLactoseIdentityUsersDtosUserEvent::FromBytes(const TArray<uint8>& Bytes)
{
    TSharedPtr<FJsonObject> JsonObject = Catalyst::Json::BytesToJsonObject(Bytes);
    return JsonObject ? Catalyst::Json::JsonObjectToStruct<FLactoseIdentityUsersDtosUserEvent>(JsonObject.ToSharedRef()) : TOptional<FLactoseIdentityUsersDtosUserEvent>();
}
