//
// This file was generated by Catalyst's Unreal compiler at 02/05/2025 17:42:48.
// It is recommended not to modify this file. Modify the source spec file instead.
//

#include "LactoseIdentityAuthDtosAuth.h"

#include "CatalystJson.h"
#include "Templates/SharedPointer.h"


TArray<uint8> FLactoseIdentityAuthDtosLoginRequest::ToBytes(const FLactoseIdentityAuthDtosLoginRequest& Object)
{
    TSharedPtr<FJsonObject> JsonObject = Catalyst::Json::StructToJsonObject(Object);
    return JsonObject ? Catalyst::Json::JsonObjectToBytes(JsonObject.ToSharedRef()) : TArray<uint8>();
}

TArray<uint8> FLactoseIdentityAuthDtosLoginRequest::ToBytes() const
{
    return ToBytes(*this);
}

TOptional<FLactoseIdentityAuthDtosLoginRequest> FLactoseIdentityAuthDtosLoginRequest::FromBytes(const TArray<uint8>& Bytes)
{
    TSharedPtr<FJsonObject> JsonObject = Catalyst::Json::BytesToJsonObject(Bytes);
    return JsonObject ? Catalyst::Json::JsonObjectToStruct<FLactoseIdentityAuthDtosLoginRequest>(JsonObject.ToSharedRef()) : TOptional<FLactoseIdentityAuthDtosLoginRequest>();
}

TArray<uint8> FLactoseIdentityAuthDtosLoginResponse::ToBytes(const FLactoseIdentityAuthDtosLoginResponse& Object)
{
    TSharedPtr<FJsonObject> JsonObject = Catalyst::Json::StructToJsonObject(Object);
    return JsonObject ? Catalyst::Json::JsonObjectToBytes(JsonObject.ToSharedRef()) : TArray<uint8>();
}

TArray<uint8> FLactoseIdentityAuthDtosLoginResponse::ToBytes() const
{
    return ToBytes(*this);
}

TOptional<FLactoseIdentityAuthDtosLoginResponse> FLactoseIdentityAuthDtosLoginResponse::FromBytes(const TArray<uint8>& Bytes)
{
    TSharedPtr<FJsonObject> JsonObject = Catalyst::Json::BytesToJsonObject(Bytes);
    return JsonObject ? Catalyst::Json::JsonObjectToStruct<FLactoseIdentityAuthDtosLoginResponse>(JsonObject.ToSharedRef()) : TOptional<FLactoseIdentityAuthDtosLoginResponse>();
}

TArray<uint8> FLactoseIdentityAuthDtosLogoutRequest::ToBytes(const FLactoseIdentityAuthDtosLogoutRequest& Object)
{
    TSharedPtr<FJsonObject> JsonObject = Catalyst::Json::StructToJsonObject(Object);
    return JsonObject ? Catalyst::Json::JsonObjectToBytes(JsonObject.ToSharedRef()) : TArray<uint8>();
}

TArray<uint8> FLactoseIdentityAuthDtosLogoutRequest::ToBytes() const
{
    return ToBytes(*this);
}

TOptional<FLactoseIdentityAuthDtosLogoutRequest> FLactoseIdentityAuthDtosLogoutRequest::FromBytes(const TArray<uint8>& Bytes)
{
    TSharedPtr<FJsonObject> JsonObject = Catalyst::Json::BytesToJsonObject(Bytes);
    return JsonObject ? Catalyst::Json::JsonObjectToStruct<FLactoseIdentityAuthDtosLogoutRequest>(JsonObject.ToSharedRef()) : TOptional<FLactoseIdentityAuthDtosLogoutRequest>();
}

TArray<uint8> FLactoseIdentityAuthDtosLogoutResponse::ToBytes(const FLactoseIdentityAuthDtosLogoutResponse& Object)
{
    TSharedPtr<FJsonObject> JsonObject = Catalyst::Json::StructToJsonObject(Object);
    return JsonObject ? Catalyst::Json::JsonObjectToBytes(JsonObject.ToSharedRef()) : TArray<uint8>();
}

TArray<uint8> FLactoseIdentityAuthDtosLogoutResponse::ToBytes() const
{
    return ToBytes(*this);
}

TOptional<FLactoseIdentityAuthDtosLogoutResponse> FLactoseIdentityAuthDtosLogoutResponse::FromBytes(const TArray<uint8>& Bytes)
{
    TSharedPtr<FJsonObject> JsonObject = Catalyst::Json::BytesToJsonObject(Bytes);
    return JsonObject ? Catalyst::Json::JsonObjectToStruct<FLactoseIdentityAuthDtosLogoutResponse>(JsonObject.ToSharedRef()) : TOptional<FLactoseIdentityAuthDtosLogoutResponse>();
}

TArray<uint8> FLactoseIdentityAuthDtosSignupRequest::ToBytes(const FLactoseIdentityAuthDtosSignupRequest& Object)
{
    TSharedPtr<FJsonObject> JsonObject = Catalyst::Json::StructToJsonObject(Object);
    return JsonObject ? Catalyst::Json::JsonObjectToBytes(JsonObject.ToSharedRef()) : TArray<uint8>();
}

TArray<uint8> FLactoseIdentityAuthDtosSignupRequest::ToBytes() const
{
    return ToBytes(*this);
}

TOptional<FLactoseIdentityAuthDtosSignupRequest> FLactoseIdentityAuthDtosSignupRequest::FromBytes(const TArray<uint8>& Bytes)
{
    TSharedPtr<FJsonObject> JsonObject = Catalyst::Json::BytesToJsonObject(Bytes);
    return JsonObject ? Catalyst::Json::JsonObjectToStruct<FLactoseIdentityAuthDtosSignupRequest>(JsonObject.ToSharedRef()) : TOptional<FLactoseIdentityAuthDtosSignupRequest>();
}

TArray<uint8> FLactoseIdentityAuthDtosSignupResponse::ToBytes(const FLactoseIdentityAuthDtosSignupResponse& Object)
{
    TSharedPtr<FJsonObject> JsonObject = Catalyst::Json::StructToJsonObject(Object);
    return JsonObject ? Catalyst::Json::JsonObjectToBytes(JsonObject.ToSharedRef()) : TArray<uint8>();
}

TArray<uint8> FLactoseIdentityAuthDtosSignupResponse::ToBytes() const
{
    return ToBytes(*this);
}

TOptional<FLactoseIdentityAuthDtosSignupResponse> FLactoseIdentityAuthDtosSignupResponse::FromBytes(const TArray<uint8>& Bytes)
{
    TSharedPtr<FJsonObject> JsonObject = Catalyst::Json::BytesToJsonObject(Bytes);
    return JsonObject ? Catalyst::Json::JsonObjectToStruct<FLactoseIdentityAuthDtosSignupResponse>(JsonObject.ToSharedRef()) : TOptional<FLactoseIdentityAuthDtosSignupResponse>();
}

TArray<uint8> FLactoseIdentityAuthDtosRefreshRequest::ToBytes(const FLactoseIdentityAuthDtosRefreshRequest& Object)
{
    TSharedPtr<FJsonObject> JsonObject = Catalyst::Json::StructToJsonObject(Object);
    return JsonObject ? Catalyst::Json::JsonObjectToBytes(JsonObject.ToSharedRef()) : TArray<uint8>();
}

TArray<uint8> FLactoseIdentityAuthDtosRefreshRequest::ToBytes() const
{
    return ToBytes(*this);
}

TOptional<FLactoseIdentityAuthDtosRefreshRequest> FLactoseIdentityAuthDtosRefreshRequest::FromBytes(const TArray<uint8>& Bytes)
{
    TSharedPtr<FJsonObject> JsonObject = Catalyst::Json::BytesToJsonObject(Bytes);
    return JsonObject ? Catalyst::Json::JsonObjectToStruct<FLactoseIdentityAuthDtosRefreshRequest>(JsonObject.ToSharedRef()) : TOptional<FLactoseIdentityAuthDtosRefreshRequest>();
}

TArray<uint8> FLactoseIdentityAuthDtosRefreshResponse::ToBytes(const FLactoseIdentityAuthDtosRefreshResponse& Object)
{
    TSharedPtr<FJsonObject> JsonObject = Catalyst::Json::StructToJsonObject(Object);
    return JsonObject ? Catalyst::Json::JsonObjectToBytes(JsonObject.ToSharedRef()) : TArray<uint8>();
}

TArray<uint8> FLactoseIdentityAuthDtosRefreshResponse::ToBytes() const
{
    return ToBytes(*this);
}

TOptional<FLactoseIdentityAuthDtosRefreshResponse> FLactoseIdentityAuthDtosRefreshResponse::FromBytes(const TArray<uint8>& Bytes)
{
    TSharedPtr<FJsonObject> JsonObject = Catalyst::Json::BytesToJsonObject(Bytes);
    return JsonObject ? Catalyst::Json::JsonObjectToStruct<FLactoseIdentityAuthDtosRefreshResponse>(JsonObject.ToSharedRef()) : TOptional<FLactoseIdentityAuthDtosRefreshResponse>();
}

TArray<uint8> FLactoseIdentityAuthDtosGetDetailsRequest::ToBytes(const FLactoseIdentityAuthDtosGetDetailsRequest& Object)
{
    TSharedPtr<FJsonObject> JsonObject = Catalyst::Json::StructToJsonObject(Object);
    return JsonObject ? Catalyst::Json::JsonObjectToBytes(JsonObject.ToSharedRef()) : TArray<uint8>();
}

TArray<uint8> FLactoseIdentityAuthDtosGetDetailsRequest::ToBytes() const
{
    return ToBytes(*this);
}

TOptional<FLactoseIdentityAuthDtosGetDetailsRequest> FLactoseIdentityAuthDtosGetDetailsRequest::FromBytes(const TArray<uint8>& Bytes)
{
    TSharedPtr<FJsonObject> JsonObject = Catalyst::Json::BytesToJsonObject(Bytes);
    return JsonObject ? Catalyst::Json::JsonObjectToStruct<FLactoseIdentityAuthDtosGetDetailsRequest>(JsonObject.ToSharedRef()) : TOptional<FLactoseIdentityAuthDtosGetDetailsRequest>();
}

TArray<uint8> FLactoseIdentityAuthDtosGetDetailsResponse::ToBytes(const FLactoseIdentityAuthDtosGetDetailsResponse& Object)
{
    TSharedPtr<FJsonObject> JsonObject = Catalyst::Json::StructToJsonObject(Object);
    return JsonObject ? Catalyst::Json::JsonObjectToBytes(JsonObject.ToSharedRef()) : TArray<uint8>();
}

TArray<uint8> FLactoseIdentityAuthDtosGetDetailsResponse::ToBytes() const
{
    return ToBytes(*this);
}

TOptional<FLactoseIdentityAuthDtosGetDetailsResponse> FLactoseIdentityAuthDtosGetDetailsResponse::FromBytes(const TArray<uint8>& Bytes)
{
    TSharedPtr<FJsonObject> JsonObject = Catalyst::Json::BytesToJsonObject(Bytes);
    return JsonObject ? Catalyst::Json::JsonObjectToStruct<FLactoseIdentityAuthDtosGetDetailsResponse>(JsonObject.ToSharedRef()) : TOptional<FLactoseIdentityAuthDtosGetDetailsResponse>();
}

TArray<uint8> FLactoseIdentityAuthDtosAuthenticateTokenRequest::ToBytes(const FLactoseIdentityAuthDtosAuthenticateTokenRequest& Object)
{
    TSharedPtr<FJsonObject> JsonObject = Catalyst::Json::StructToJsonObject(Object);
    return JsonObject ? Catalyst::Json::JsonObjectToBytes(JsonObject.ToSharedRef()) : TArray<uint8>();
}

TArray<uint8> FLactoseIdentityAuthDtosAuthenticateTokenRequest::ToBytes() const
{
    return ToBytes(*this);
}

TOptional<FLactoseIdentityAuthDtosAuthenticateTokenRequest> FLactoseIdentityAuthDtosAuthenticateTokenRequest::FromBytes(const TArray<uint8>& Bytes)
{
    TSharedPtr<FJsonObject> JsonObject = Catalyst::Json::BytesToJsonObject(Bytes);
    return JsonObject ? Catalyst::Json::JsonObjectToStruct<FLactoseIdentityAuthDtosAuthenticateTokenRequest>(JsonObject.ToSharedRef()) : TOptional<FLactoseIdentityAuthDtosAuthenticateTokenRequest>();
}

TArray<uint8> FLactoseIdentityAuthDtosAuthenticateTokenResponse::ToBytes(const FLactoseIdentityAuthDtosAuthenticateTokenResponse& Object)
{
    TSharedPtr<FJsonObject> JsonObject = Catalyst::Json::StructToJsonObject(Object);
    return JsonObject ? Catalyst::Json::JsonObjectToBytes(JsonObject.ToSharedRef()) : TArray<uint8>();
}

TArray<uint8> FLactoseIdentityAuthDtosAuthenticateTokenResponse::ToBytes() const
{
    return ToBytes(*this);
}

TOptional<FLactoseIdentityAuthDtosAuthenticateTokenResponse> FLactoseIdentityAuthDtosAuthenticateTokenResponse::FromBytes(const TArray<uint8>& Bytes)
{
    TSharedPtr<FJsonObject> JsonObject = Catalyst::Json::BytesToJsonObject(Bytes);
    return JsonObject ? Catalyst::Json::JsonObjectToStruct<FLactoseIdentityAuthDtosAuthenticateTokenResponse>(JsonObject.ToSharedRef()) : TOptional<FLactoseIdentityAuthDtosAuthenticateTokenResponse>();
}

TArray<uint8> FLactoseIdentityAuthDtosUserLoggedInEvent::ToBytes(const FLactoseIdentityAuthDtosUserLoggedInEvent& Object)
{
    TSharedPtr<FJsonObject> JsonObject = Catalyst::Json::StructToJsonObject(Object);
    return JsonObject ? Catalyst::Json::JsonObjectToBytes(JsonObject.ToSharedRef()) : TArray<uint8>();
}

TArray<uint8> FLactoseIdentityAuthDtosUserLoggedInEvent::ToBytes() const
{
    return ToBytes(*this);
}

TOptional<FLactoseIdentityAuthDtosUserLoggedInEvent> FLactoseIdentityAuthDtosUserLoggedInEvent::FromBytes(const TArray<uint8>& Bytes)
{
    TSharedPtr<FJsonObject> JsonObject = Catalyst::Json::BytesToJsonObject(Bytes);
    return JsonObject ? Catalyst::Json::JsonObjectToStruct<FLactoseIdentityAuthDtosUserLoggedInEvent>(JsonObject.ToSharedRef()) : TOptional<FLactoseIdentityAuthDtosUserLoggedInEvent>();
}
