//
// This file was generated by Catalyst's Unreal compiler at 02/05/2025 17:42:48.
// It is recommended not to modify this file. Modify the source spec file instead.
//

#pragma once

#include "Misc/DateTime.h"

#include "LactoseIdentityAuthDtosAuth.generated.h"

USTRUCT(BlueprintType)
struct FLactoseIdentityAuthDtosLoginRequest
{
    GENERATED_BODY()

    UPROPERTY(EditAnywhere)
    FString Email;

    UPROPERTY(EditAnywhere)
    FString Password;

    static TArray<uint8> ToBytes(const FLactoseIdentityAuthDtosLoginRequest& Object);

    TArray<uint8> ToBytes() const;

    static TOptional<FLactoseIdentityAuthDtosLoginRequest> FromBytes(const TArray<uint8>& Bytes);
};

USTRUCT(BlueprintType)
struct FLactoseIdentityAuthDtosLoginResponse
{
    GENERATED_BODY()

    UPROPERTY(EditAnywhere)
    FString AccessToken;

    UPROPERTY(EditAnywhere)
    FString RefreshToken;

    static TArray<uint8> ToBytes(const FLactoseIdentityAuthDtosLoginResponse& Object);

    TArray<uint8> ToBytes() const;

    static TOptional<FLactoseIdentityAuthDtosLoginResponse> FromBytes(const TArray<uint8>& Bytes);
};

USTRUCT(BlueprintType)
struct FLactoseIdentityAuthDtosLogoutRequest
{
    GENERATED_BODY()


    static TArray<uint8> ToBytes(const FLactoseIdentityAuthDtosLogoutRequest& Object);

    TArray<uint8> ToBytes() const;

    static TOptional<FLactoseIdentityAuthDtosLogoutRequest> FromBytes(const TArray<uint8>& Bytes);
};

USTRUCT(BlueprintType)
struct FLactoseIdentityAuthDtosLogoutResponse
{
    GENERATED_BODY()


    static TArray<uint8> ToBytes(const FLactoseIdentityAuthDtosLogoutResponse& Object);

    TArray<uint8> ToBytes() const;

    static TOptional<FLactoseIdentityAuthDtosLogoutResponse> FromBytes(const TArray<uint8>& Bytes);
};

USTRUCT(BlueprintType)
struct FLactoseIdentityAuthDtosSignupRequest
{
    GENERATED_BODY()

    UPROPERTY(EditAnywhere)
    FString Email;

    UPROPERTY(EditAnywhere)
    FString Password;

    UPROPERTY(EditAnywhere)
    FString DisplayName;

    static TArray<uint8> ToBytes(const FLactoseIdentityAuthDtosSignupRequest& Object);

    TArray<uint8> ToBytes() const;

    static TOptional<FLactoseIdentityAuthDtosSignupRequest> FromBytes(const TArray<uint8>& Bytes);
};

USTRUCT(BlueprintType)
struct FLactoseIdentityAuthDtosSignupResponse
{
    GENERATED_BODY()

    UPROPERTY(EditAnywhere)
    FString AccessToken;

    UPROPERTY(EditAnywhere)
    FString RefreshToken;

    static TArray<uint8> ToBytes(const FLactoseIdentityAuthDtosSignupResponse& Object);

    TArray<uint8> ToBytes() const;

    static TOptional<FLactoseIdentityAuthDtosSignupResponse> FromBytes(const TArray<uint8>& Bytes);
};

USTRUCT(BlueprintType)
struct FLactoseIdentityAuthDtosRefreshRequest
{
    GENERATED_BODY()

    UPROPERTY(EditAnywhere)
    TOptional<FString> RefreshToken;

    static TArray<uint8> ToBytes(const FLactoseIdentityAuthDtosRefreshRequest& Object);

    TArray<uint8> ToBytes() const;

    static TOptional<FLactoseIdentityAuthDtosRefreshRequest> FromBytes(const TArray<uint8>& Bytes);
};

USTRUCT(BlueprintType)
struct FLactoseIdentityAuthDtosRefreshResponse
{
    GENERATED_BODY()

    UPROPERTY(EditAnywhere)
    FString AccessToken;

    UPROPERTY(EditAnywhere)
    FString RefreshToken;

    static TArray<uint8> ToBytes(const FLactoseIdentityAuthDtosRefreshResponse& Object);

    TArray<uint8> ToBytes() const;

    static TOptional<FLactoseIdentityAuthDtosRefreshResponse> FromBytes(const TArray<uint8>& Bytes);
};

USTRUCT(BlueprintType)
struct FLactoseIdentityAuthDtosGetDetailsRequest
{
    GENERATED_BODY()


    static TArray<uint8> ToBytes(const FLactoseIdentityAuthDtosGetDetailsRequest& Object);

    TArray<uint8> ToBytes() const;

    static TOptional<FLactoseIdentityAuthDtosGetDetailsRequest> FromBytes(const TArray<uint8>& Bytes);
};

USTRUCT(BlueprintType)
struct FLactoseIdentityAuthDtosGetDetailsResponse
{
    GENERATED_BODY()

    UPROPERTY(EditAnywhere)
    TOptional<FString> Id;

    UPROPERTY(EditAnywhere)
    TOptional<FString> DisplayName;

    UPROPERTY(EditAnywhere)
    TOptional<FString> Email;

    UPROPERTY(EditAnywhere)
    TArray<FString> Roles;

    UPROPERTY(EditAnywhere)
    TArray<FString> Permissions;

    static TArray<uint8> ToBytes(const FLactoseIdentityAuthDtosGetDetailsResponse& Object);

    TArray<uint8> ToBytes() const;

    static TOptional<FLactoseIdentityAuthDtosGetDetailsResponse> FromBytes(const TArray<uint8>& Bytes);
};

USTRUCT(BlueprintType)
struct FLactoseIdentityAuthDtosAuthenticateTokenRequest
{
    GENERATED_BODY()

    UPROPERTY(EditAnywhere)
    FString AccessToken;

    UPROPERTY(EditAnywhere)
    TOptional<FString> Audience;

    static TArray<uint8> ToBytes(const FLactoseIdentityAuthDtosAuthenticateTokenRequest& Object);

    TArray<uint8> ToBytes() const;

    static TOptional<FLactoseIdentityAuthDtosAuthenticateTokenRequest> FromBytes(const TArray<uint8>& Bytes);
};

USTRUCT(BlueprintType)
struct FLactoseIdentityAuthDtosAuthenticateTokenResponse
{
    GENERATED_BODY()

    UPROPERTY(EditAnywhere)
    TArray<FString> UserRoles;

    static TArray<uint8> ToBytes(const FLactoseIdentityAuthDtosAuthenticateTokenResponse& Object);

    TArray<uint8> ToBytes() const;

    static TOptional<FLactoseIdentityAuthDtosAuthenticateTokenResponse> FromBytes(const TArray<uint8>& Bytes);
};

USTRUCT(BlueprintType)
struct FLactoseIdentityAuthDtosUserLoggedInEvent
{
    GENERATED_BODY()

    UPROPERTY(EditAnywhere)
    FString UserId;

    UPROPERTY(EditAnywhere)
    FDateTime TimeLastLoggedIn;

    static TArray<uint8> ToBytes(const FLactoseIdentityAuthDtosUserLoggedInEvent& Object);

    TArray<uint8> ToBytes() const;

    static TOptional<FLactoseIdentityAuthDtosUserLoggedInEvent> FromBytes(const TArray<uint8>& Bytes);
};

