//
// This file was generated by Catalyst's Unreal compiler at 02/05/2025 17:42:48.
// It is recommended not to modify this file. Modify the source spec file instead.
//

#pragma once

#include "LactoseIdentityRolesDtosRoles.generated.h"

USTRUCT(BlueprintType)
struct FLactoseIdentityRolesDtosQueryRolesRequest
{
    GENERATED_BODY()


    static TArray<uint8> ToBytes(const FLactoseIdentityRolesDtosQueryRolesRequest& Object);

    TArray<uint8> ToBytes() const;

    static TOptional<FLactoseIdentityRolesDtosQueryRolesRequest> FromBytes(const TArray<uint8>& Bytes);
};

USTRUCT(BlueprintType)
struct FLactoseIdentityRolesDtosQueryRolesResponse
{
    GENERATED_BODY()

    UPROPERTY(EditAnywhere)
    TArray<FString> RoleIds;

    static TArray<uint8> ToBytes(const FLactoseIdentityRolesDtosQueryRolesResponse& Object);

    TArray<uint8> ToBytes() const;

    static TOptional<FLactoseIdentityRolesDtosQueryRolesResponse> FromBytes(const TArray<uint8>& Bytes);
};

USTRUCT(BlueprintType)
struct FLactoseIdentityRolesDtosGetRolesRequest
{
    GENERATED_BODY()

    UPROPERTY(EditAnywhere)
    TArray<FString> RoleIds;

    static TArray<uint8> ToBytes(const FLactoseIdentityRolesDtosGetRolesRequest& Object);

    TArray<uint8> ToBytes() const;

    static TOptional<FLactoseIdentityRolesDtosGetRolesRequest> FromBytes(const TArray<uint8>& Bytes);
};

USTRUCT(BlueprintType)
struct FLactoseIdentityRolesDtosGetRoleResponse
{
    GENERATED_BODY()

    UPROPERTY(EditAnywhere)
    FString Id;

    UPROPERTY(EditAnywhere)
    FString RoleName;

    UPROPERTY(EditAnywhere)
    TArray<FString> Permissions;

    static TArray<uint8> ToBytes(const FLactoseIdentityRolesDtosGetRoleResponse& Object);

    TArray<uint8> ToBytes() const;

    static TOptional<FLactoseIdentityRolesDtosGetRoleResponse> FromBytes(const TArray<uint8>& Bytes);
};

USTRUCT(BlueprintType)
struct FLactoseIdentityRolesDtosGetRolesResponse
{
    GENERATED_BODY()

    UPROPERTY(EditAnywhere)
    TArray<FLactoseIdentityRolesDtosGetRoleResponse> Roles;

    static TArray<uint8> ToBytes(const FLactoseIdentityRolesDtosGetRolesResponse& Object);

    TArray<uint8> ToBytes() const;

    static TOptional<FLactoseIdentityRolesDtosGetRolesResponse> FromBytes(const TArray<uint8>& Bytes);
};

USTRUCT(BlueprintType)
struct FLactoseIdentityRolesDtosCreateRoleRequest
{
    GENERATED_BODY()

    UPROPERTY(EditAnywhere)
    FString Id;

    UPROPERTY(EditAnywhere)
    FString RoleName;

    UPROPERTY(EditAnywhere)
    TArray<FString> Permissions;

    static TArray<uint8> ToBytes(const FLactoseIdentityRolesDtosCreateRoleRequest& Object);

    TArray<uint8> ToBytes() const;

    static TOptional<FLactoseIdentityRolesDtosCreateRoleRequest> FromBytes(const TArray<uint8>& Bytes);
};

USTRUCT(BlueprintType)
struct FLactoseIdentityRolesDtosRoleEvent
{
    GENERATED_BODY()

    UPROPERTY(EditAnywhere)
    TArray<FString> RoleIds;

    static TArray<uint8> ToBytes(const FLactoseIdentityRolesDtosRoleEvent& Object);

    TArray<uint8> ToBytes() const;

    static TOptional<FLactoseIdentityRolesDtosRoleEvent> FromBytes(const TArray<uint8>& Bytes);
};

