//
// This file was generated by Catalyst's Unreal compiler at 02/05/2025 17:42:48.
// It is recommended not to modify this file. Modify the source spec file instead.
//

#include "LactoseIdentityRolesDtosRoles.h"

#include "CatalystJson.h"
#include "Templates/SharedPointer.h"


TArray<uint8> FLactoseIdentityRolesDtosQueryRolesRequest::ToBytes(const FLactoseIdentityRolesDtosQueryRolesRequest& Object)
{
    TSharedPtr<FJsonObject> JsonObject = Catalyst::Json::StructToJsonObject(Object);
    return JsonObject ? Catalyst::Json::JsonObjectToBytes(JsonObject.ToSharedRef()) : TArray<uint8>();
}

TArray<uint8> FLactoseIdentityRolesDtosQueryRolesRequest::ToBytes() const
{
    return ToBytes(*this);
}

TOptional<FLactoseIdentityRolesDtosQueryRolesRequest> FLactoseIdentityRolesDtosQueryRolesRequest::FromBytes(const TArray<uint8>& Bytes)
{
    TSharedPtr<FJsonObject> JsonObject = Catalyst::Json::BytesToJsonObject(Bytes);
    return JsonObject ? Catalyst::Json::JsonObjectToStruct<FLactoseIdentityRolesDtosQueryRolesRequest>(JsonObject.ToSharedRef()) : TOptional<FLactoseIdentityRolesDtosQueryRolesRequest>();
}

TArray<uint8> FLactoseIdentityRolesDtosQueryRolesResponse::ToBytes(const FLactoseIdentityRolesDtosQueryRolesResponse& Object)
{
    TSharedPtr<FJsonObject> JsonObject = Catalyst::Json::StructToJsonObject(Object);
    return JsonObject ? Catalyst::Json::JsonObjectToBytes(JsonObject.ToSharedRef()) : TArray<uint8>();
}

TArray<uint8> FLactoseIdentityRolesDtosQueryRolesResponse::ToBytes() const
{
    return ToBytes(*this);
}

TOptional<FLactoseIdentityRolesDtosQueryRolesResponse> FLactoseIdentityRolesDtosQueryRolesResponse::FromBytes(const TArray<uint8>& Bytes)
{
    TSharedPtr<FJsonObject> JsonObject = Catalyst::Json::BytesToJsonObject(Bytes);
    return JsonObject ? Catalyst::Json::JsonObjectToStruct<FLactoseIdentityRolesDtosQueryRolesResponse>(JsonObject.ToSharedRef()) : TOptional<FLactoseIdentityRolesDtosQueryRolesResponse>();
}

TArray<uint8> FLactoseIdentityRolesDtosGetRolesRequest::ToBytes(const FLactoseIdentityRolesDtosGetRolesRequest& Object)
{
    TSharedPtr<FJsonObject> JsonObject = Catalyst::Json::StructToJsonObject(Object);
    return JsonObject ? Catalyst::Json::JsonObjectToBytes(JsonObject.ToSharedRef()) : TArray<uint8>();
}

TArray<uint8> FLactoseIdentityRolesDtosGetRolesRequest::ToBytes() const
{
    return ToBytes(*this);
}

TOptional<FLactoseIdentityRolesDtosGetRolesRequest> FLactoseIdentityRolesDtosGetRolesRequest::FromBytes(const TArray<uint8>& Bytes)
{
    TSharedPtr<FJsonObject> JsonObject = Catalyst::Json::BytesToJsonObject(Bytes);
    return JsonObject ? Catalyst::Json::JsonObjectToStruct<FLactoseIdentityRolesDtosGetRolesRequest>(JsonObject.ToSharedRef()) : TOptional<FLactoseIdentityRolesDtosGetRolesRequest>();
}

TArray<uint8> FLactoseIdentityRolesDtosGetRoleResponse::ToBytes(const FLactoseIdentityRolesDtosGetRoleResponse& Object)
{
    TSharedPtr<FJsonObject> JsonObject = Catalyst::Json::StructToJsonObject(Object);
    return JsonObject ? Catalyst::Json::JsonObjectToBytes(JsonObject.ToSharedRef()) : TArray<uint8>();
}

TArray<uint8> FLactoseIdentityRolesDtosGetRoleResponse::ToBytes() const
{
    return ToBytes(*this);
}

TOptional<FLactoseIdentityRolesDtosGetRoleResponse> FLactoseIdentityRolesDtosGetRoleResponse::FromBytes(const TArray<uint8>& Bytes)
{
    TSharedPtr<FJsonObject> JsonObject = Catalyst::Json::BytesToJsonObject(Bytes);
    return JsonObject ? Catalyst::Json::JsonObjectToStruct<FLactoseIdentityRolesDtosGetRoleResponse>(JsonObject.ToSharedRef()) : TOptional<FLactoseIdentityRolesDtosGetRoleResponse>();
}

TArray<uint8> FLactoseIdentityRolesDtosGetRolesResponse::ToBytes(const FLactoseIdentityRolesDtosGetRolesResponse& Object)
{
    TSharedPtr<FJsonObject> JsonObject = Catalyst::Json::StructToJsonObject(Object);
    return JsonObject ? Catalyst::Json::JsonObjectToBytes(JsonObject.ToSharedRef()) : TArray<uint8>();
}

TArray<uint8> FLactoseIdentityRolesDtosGetRolesResponse::ToBytes() const
{
    return ToBytes(*this);
}

TOptional<FLactoseIdentityRolesDtosGetRolesResponse> FLactoseIdentityRolesDtosGetRolesResponse::FromBytes(const TArray<uint8>& Bytes)
{
    TSharedPtr<FJsonObject> JsonObject = Catalyst::Json::BytesToJsonObject(Bytes);
    return JsonObject ? Catalyst::Json::JsonObjectToStruct<FLactoseIdentityRolesDtosGetRolesResponse>(JsonObject.ToSharedRef()) : TOptional<FLactoseIdentityRolesDtosGetRolesResponse>();
}

TArray<uint8> FLactoseIdentityRolesDtosCreateRoleRequest::ToBytes(const FLactoseIdentityRolesDtosCreateRoleRequest& Object)
{
    TSharedPtr<FJsonObject> JsonObject = Catalyst::Json::StructToJsonObject(Object);
    return JsonObject ? Catalyst::Json::JsonObjectToBytes(JsonObject.ToSharedRef()) : TArray<uint8>();
}

TArray<uint8> FLactoseIdentityRolesDtosCreateRoleRequest::ToBytes() const
{
    return ToBytes(*this);
}

TOptional<FLactoseIdentityRolesDtosCreateRoleRequest> FLactoseIdentityRolesDtosCreateRoleRequest::FromBytes(const TArray<uint8>& Bytes)
{
    TSharedPtr<FJsonObject> JsonObject = Catalyst::Json::BytesToJsonObject(Bytes);
    return JsonObject ? Catalyst::Json::JsonObjectToStruct<FLactoseIdentityRolesDtosCreateRoleRequest>(JsonObject.ToSharedRef()) : TOptional<FLactoseIdentityRolesDtosCreateRoleRequest>();
}

TArray<uint8> FLactoseIdentityRolesDtosRoleEvent::ToBytes(const FLactoseIdentityRolesDtosRoleEvent& Object)
{
    TSharedPtr<FJsonObject> JsonObject = Catalyst::Json::StructToJsonObject(Object);
    return JsonObject ? Catalyst::Json::JsonObjectToBytes(JsonObject.ToSharedRef()) : TArray<uint8>();
}

TArray<uint8> FLactoseIdentityRolesDtosRoleEvent::ToBytes() const
{
    return ToBytes(*this);
}

TOptional<FLactoseIdentityRolesDtosRoleEvent> FLactoseIdentityRolesDtosRoleEvent::FromBytes(const TArray<uint8>& Bytes)
{
    TSharedPtr<FJsonObject> JsonObject = Catalyst::Json::BytesToJsonObject(Bytes);
    return JsonObject ? Catalyst::Json::JsonObjectToStruct<FLactoseIdentityRolesDtosRoleEvent>(JsonObject.ToSharedRef()) : TOptional<FLactoseIdentityRolesDtosRoleEvent>();
}
