//
// This file was generated by Catalyst's Unreal compiler at 02/05/2025 17:42:48.
// It is recommended not to modify this file. Modify the source spec file instead.
//

#include "LactoseTasks.h"

#include "CatalystJson.h"
#include "Templates/SharedPointer.h"


TArray<uint8> FLactoseTasksItemRewardDto::ToBytes(const FLactoseTasksItemRewardDto& Object)
{
    TSharedPtr<FJsonObject> JsonObject = Catalyst::Json::StructToJsonObject(Object);
    return JsonObject ? Catalyst::Json::JsonObjectToBytes(JsonObject.ToSharedRef()) : TArray<uint8>();
}

TArray<uint8> FLactoseTasksItemRewardDto::ToBytes() const
{
    return ToBytes(*this);
}

TOptional<FLactoseTasksItemRewardDto> FLactoseTasksItemRewardDto::FromBytes(const TArray<uint8>& Bytes)
{
    TSharedPtr<FJsonObject> JsonObject = Catalyst::Json::BytesToJsonObject(Bytes);
    return JsonObject ? Catalyst::Json::JsonObjectToStruct<FLactoseTasksItemRewardDto>(JsonObject.ToSharedRef()) : TOptional<FLactoseTasksItemRewardDto>();
}

TArray<uint8> FLactoseTasksTriggerDto::ToBytes(const FLactoseTasksTriggerDto& Object)
{
    TSharedPtr<FJsonObject> JsonObject = Catalyst::Json::StructToJsonObject(Object);
    return JsonObject ? Catalyst::Json::JsonObjectToBytes(JsonObject.ToSharedRef()) : TArray<uint8>();
}

TArray<uint8> FLactoseTasksTriggerDto::ToBytes() const
{
    return ToBytes(*this);
}

TOptional<FLactoseTasksTriggerDto> FLactoseTasksTriggerDto::FromBytes(const TArray<uint8>& Bytes)
{
    TSharedPtr<FJsonObject> JsonObject = Catalyst::Json::BytesToJsonObject(Bytes);
    return JsonObject ? Catalyst::Json::JsonObjectToStruct<FLactoseTasksTriggerDto>(JsonObject.ToSharedRef()) : TOptional<FLactoseTasksTriggerDto>();
}

TArray<uint8> FLactoseTasksQueryTasksRequest::ToBytes(const FLactoseTasksQueryTasksRequest& Object)
{
    TSharedPtr<FJsonObject> JsonObject = Catalyst::Json::StructToJsonObject(Object);
    return JsonObject ? Catalyst::Json::JsonObjectToBytes(JsonObject.ToSharedRef()) : TArray<uint8>();
}

TArray<uint8> FLactoseTasksQueryTasksRequest::ToBytes() const
{
    return ToBytes(*this);
}

TOptional<FLactoseTasksQueryTasksRequest> FLactoseTasksQueryTasksRequest::FromBytes(const TArray<uint8>& Bytes)
{
    TSharedPtr<FJsonObject> JsonObject = Catalyst::Json::BytesToJsonObject(Bytes);
    return JsonObject ? Catalyst::Json::JsonObjectToStruct<FLactoseTasksQueryTasksRequest>(JsonObject.ToSharedRef()) : TOptional<FLactoseTasksQueryTasksRequest>();
}

TArray<uint8> FLactoseTasksQueryTasksResponse::ToBytes(const FLactoseTasksQueryTasksResponse& Object)
{
    TSharedPtr<FJsonObject> JsonObject = Catalyst::Json::StructToJsonObject(Object);
    return JsonObject ? Catalyst::Json::JsonObjectToBytes(JsonObject.ToSharedRef()) : TArray<uint8>();
}

TArray<uint8> FLactoseTasksQueryTasksResponse::ToBytes() const
{
    return ToBytes(*this);
}

TOptional<FLactoseTasksQueryTasksResponse> FLactoseTasksQueryTasksResponse::FromBytes(const TArray<uint8>& Bytes)
{
    TSharedPtr<FJsonObject> JsonObject = Catalyst::Json::BytesToJsonObject(Bytes);
    return JsonObject ? Catalyst::Json::JsonObjectToStruct<FLactoseTasksQueryTasksResponse>(JsonObject.ToSharedRef()) : TOptional<FLactoseTasksQueryTasksResponse>();
}

TArray<uint8> FLactoseTasksGetTasksRequest::ToBytes(const FLactoseTasksGetTasksRequest& Object)
{
    TSharedPtr<FJsonObject> JsonObject = Catalyst::Json::StructToJsonObject(Object);
    return JsonObject ? Catalyst::Json::JsonObjectToBytes(JsonObject.ToSharedRef()) : TArray<uint8>();
}

TArray<uint8> FLactoseTasksGetTasksRequest::ToBytes() const
{
    return ToBytes(*this);
}

TOptional<FLactoseTasksGetTasksRequest> FLactoseTasksGetTasksRequest::FromBytes(const TArray<uint8>& Bytes)
{
    TSharedPtr<FJsonObject> JsonObject = Catalyst::Json::BytesToJsonObject(Bytes);
    return JsonObject ? Catalyst::Json::JsonObjectToStruct<FLactoseTasksGetTasksRequest>(JsonObject.ToSharedRef()) : TOptional<FLactoseTasksGetTasksRequest>();
}

TArray<uint8> FLactoseTasksGetTaskResponse::ToBytes(const FLactoseTasksGetTaskResponse& Object)
{
    TSharedPtr<FJsonObject> JsonObject = Catalyst::Json::StructToJsonObject(Object);
    return JsonObject ? Catalyst::Json::JsonObjectToBytes(JsonObject.ToSharedRef()) : TArray<uint8>();
}

TArray<uint8> FLactoseTasksGetTaskResponse::ToBytes() const
{
    return ToBytes(*this);
}

TOptional<FLactoseTasksGetTaskResponse> FLactoseTasksGetTaskResponse::FromBytes(const TArray<uint8>& Bytes)
{
    TSharedPtr<FJsonObject> JsonObject = Catalyst::Json::BytesToJsonObject(Bytes);
    return JsonObject ? Catalyst::Json::JsonObjectToStruct<FLactoseTasksGetTaskResponse>(JsonObject.ToSharedRef()) : TOptional<FLactoseTasksGetTaskResponse>();
}

TArray<uint8> FLactoseTasksGetTasksResponse::ToBytes(const FLactoseTasksGetTasksResponse& Object)
{
    TSharedPtr<FJsonObject> JsonObject = Catalyst::Json::StructToJsonObject(Object);
    return JsonObject ? Catalyst::Json::JsonObjectToBytes(JsonObject.ToSharedRef()) : TArray<uint8>();
}

TArray<uint8> FLactoseTasksGetTasksResponse::ToBytes() const
{
    return ToBytes(*this);
}

TOptional<FLactoseTasksGetTasksResponse> FLactoseTasksGetTasksResponse::FromBytes(const TArray<uint8>& Bytes)
{
    TSharedPtr<FJsonObject> JsonObject = Catalyst::Json::BytesToJsonObject(Bytes);
    return JsonObject ? Catalyst::Json::JsonObjectToStruct<FLactoseTasksGetTasksResponse>(JsonObject.ToSharedRef()) : TOptional<FLactoseTasksGetTasksResponse>();
}

TArray<uint8> FLactoseTasksCreateTaskRequest::ToBytes(const FLactoseTasksCreateTaskRequest& Object)
{
    TSharedPtr<FJsonObject> JsonObject = Catalyst::Json::StructToJsonObject(Object);
    return JsonObject ? Catalyst::Json::JsonObjectToBytes(JsonObject.ToSharedRef()) : TArray<uint8>();
}

TArray<uint8> FLactoseTasksCreateTaskRequest::ToBytes() const
{
    return ToBytes(*this);
}

TOptional<FLactoseTasksCreateTaskRequest> FLactoseTasksCreateTaskRequest::FromBytes(const TArray<uint8>& Bytes)
{
    TSharedPtr<FJsonObject> JsonObject = Catalyst::Json::BytesToJsonObject(Bytes);
    return JsonObject ? Catalyst::Json::JsonObjectToStruct<FLactoseTasksCreateTaskRequest>(JsonObject.ToSharedRef()) : TOptional<FLactoseTasksCreateTaskRequest>();
}

TArray<uint8> FLactoseTasksUpdateTaskRequest::ToBytes(const FLactoseTasksUpdateTaskRequest& Object)
{
    TSharedPtr<FJsonObject> JsonObject = Catalyst::Json::StructToJsonObject(Object);
    return JsonObject ? Catalyst::Json::JsonObjectToBytes(JsonObject.ToSharedRef()) : TArray<uint8>();
}

TArray<uint8> FLactoseTasksUpdateTaskRequest::ToBytes() const
{
    return ToBytes(*this);
}

TOptional<FLactoseTasksUpdateTaskRequest> FLactoseTasksUpdateTaskRequest::FromBytes(const TArray<uint8>& Bytes)
{
    TSharedPtr<FJsonObject> JsonObject = Catalyst::Json::BytesToJsonObject(Bytes);
    return JsonObject ? Catalyst::Json::JsonObjectToStruct<FLactoseTasksUpdateTaskRequest>(JsonObject.ToSharedRef()) : TOptional<FLactoseTasksUpdateTaskRequest>();
}

TArray<uint8> FLactoseTasksDeleteTasksRequest::ToBytes(const FLactoseTasksDeleteTasksRequest& Object)
{
    TSharedPtr<FJsonObject> JsonObject = Catalyst::Json::StructToJsonObject(Object);
    return JsonObject ? Catalyst::Json::JsonObjectToBytes(JsonObject.ToSharedRef()) : TArray<uint8>();
}

TArray<uint8> FLactoseTasksDeleteTasksRequest::ToBytes() const
{
    return ToBytes(*this);
}

TOptional<FLactoseTasksDeleteTasksRequest> FLactoseTasksDeleteTasksRequest::FromBytes(const TArray<uint8>& Bytes)
{
    TSharedPtr<FJsonObject> JsonObject = Catalyst::Json::BytesToJsonObject(Bytes);
    return JsonObject ? Catalyst::Json::JsonObjectToStruct<FLactoseTasksDeleteTasksRequest>(JsonObject.ToSharedRef()) : TOptional<FLactoseTasksDeleteTasksRequest>();
}

TArray<uint8> FLactoseTasksDeleteTasksResponse::ToBytes(const FLactoseTasksDeleteTasksResponse& Object)
{
    TSharedPtr<FJsonObject> JsonObject = Catalyst::Json::StructToJsonObject(Object);
    return JsonObject ? Catalyst::Json::JsonObjectToBytes(JsonObject.ToSharedRef()) : TArray<uint8>();
}

TArray<uint8> FLactoseTasksDeleteTasksResponse::ToBytes() const
{
    return ToBytes(*this);
}

TOptional<FLactoseTasksDeleteTasksResponse> FLactoseTasksDeleteTasksResponse::FromBytes(const TArray<uint8>& Bytes)
{
    TSharedPtr<FJsonObject> JsonObject = Catalyst::Json::BytesToJsonObject(Bytes);
    return JsonObject ? Catalyst::Json::JsonObjectToStruct<FLactoseTasksDeleteTasksResponse>(JsonObject.ToSharedRef()) : TOptional<FLactoseTasksDeleteTasksResponse>();
}

TArray<uint8> FLactoseTasksTaskEvent::ToBytes(const FLactoseTasksTaskEvent& Object)
{
    TSharedPtr<FJsonObject> JsonObject = Catalyst::Json::StructToJsonObject(Object);
    return JsonObject ? Catalyst::Json::JsonObjectToBytes(JsonObject.ToSharedRef()) : TArray<uint8>();
}

TArray<uint8> FLactoseTasksTaskEvent::ToBytes() const
{
    return ToBytes(*this);
}

TOptional<FLactoseTasksTaskEvent> FLactoseTasksTaskEvent::FromBytes(const TArray<uint8>& Bytes)
{
    TSharedPtr<FJsonObject> JsonObject = Catalyst::Json::BytesToJsonObject(Bytes);
    return JsonObject ? Catalyst::Json::JsonObjectToStruct<FLactoseTasksTaskEvent>(JsonObject.ToSharedRef()) : TOptional<FLactoseTasksTaskEvent>();
}
