//
// This file was generated by Catalyst's Unreal compiler at 02/05/2025 17:42:48.
// It is recommended not to modify this file. Modify the source spec file instead.
//

#pragma once

#include "StructUtils/InstancedStruct.h"

#include "LactoseTasks.generated.h"

USTRUCT(BlueprintType)
struct FLactoseTasksItemRewardDto
{
    GENERATED_BODY()

    UPROPERTY(EditAnywhere, BlueprintReadWrite)
    FString ItemId;

    UPROPERTY(EditAnywhere, BlueprintReadWrite)
    int32 Quantity = 0;

    static TArray<uint8> ToBytes(const FLactoseTasksItemRewardDto& Object);

    TArray<uint8> ToBytes() const;

    static TOptional<FLactoseTasksItemRewardDto> FromBytes(const TArray<uint8>& Bytes);
};

USTRUCT(BlueprintType)
struct FLactoseTasksTriggerDto
{
    GENERATED_BODY()

    UPROPERTY(EditAnywhere, BlueprintReadWrite)
    FString Topic;

    UPROPERTY(EditAnywhere, BlueprintReadWrite)
    FString Handler = "default";

    UPROPERTY(EditAnywhere, BlueprintReadWrite)
    TOptional<FInstancedStruct> Config;

    static TArray<uint8> ToBytes(const FLactoseTasksTriggerDto& Object);

    TArray<uint8> ToBytes() const;

    static TOptional<FLactoseTasksTriggerDto> FromBytes(const TArray<uint8>& Bytes);
};

USTRUCT(BlueprintType)
struct FLactoseTasksQueryTasksRequest
{
    GENERATED_BODY()


    static TArray<uint8> ToBytes(const FLactoseTasksQueryTasksRequest& Object);

    TArray<uint8> ToBytes() const;

    static TOptional<FLactoseTasksQueryTasksRequest> FromBytes(const TArray<uint8>& Bytes);
};

USTRUCT(BlueprintType)
struct FLactoseTasksQueryTasksResponse
{
    GENERATED_BODY()

    UPROPERTY(EditAnywhere, BlueprintReadWrite)
    TArray<FString> TaskIds;

    static TArray<uint8> ToBytes(const FLactoseTasksQueryTasksResponse& Object);

    TArray<uint8> ToBytes() const;

    static TOptional<FLactoseTasksQueryTasksResponse> FromBytes(const TArray<uint8>& Bytes);
};

USTRUCT(BlueprintType)
struct FLactoseTasksGetTasksRequest
{
    GENERATED_BODY()

    UPROPERTY(EditAnywhere, BlueprintReadWrite)
    TArray<FString> TaskIds;

    static TArray<uint8> ToBytes(const FLactoseTasksGetTasksRequest& Object);

    TArray<uint8> ToBytes() const;

    static TOptional<FLactoseTasksGetTasksRequest> FromBytes(const TArray<uint8>& Bytes);
};

USTRUCT(BlueprintType)
struct FLactoseTasksGetTaskResponse
{
    GENERATED_BODY()

    UPROPERTY(EditAnywhere, BlueprintReadWrite)
    FString Id;

    UPROPERTY(EditAnywhere, BlueprintReadWrite)
    FString Name;

    UPROPERTY(EditAnywhere, BlueprintReadWrite)
    TOptional<FString> Description;

    UPROPERTY(EditAnywhere, BlueprintReadWrite)
    double RequiredProgress = 0;

    UPROPERTY(EditAnywhere, BlueprintReadWrite)
    TArray<FLactoseTasksItemRewardDto> Rewards;

    static TArray<uint8> ToBytes(const FLactoseTasksGetTaskResponse& Object);

    TArray<uint8> ToBytes() const;

    static TOptional<FLactoseTasksGetTaskResponse> FromBytes(const TArray<uint8>& Bytes);
};

USTRUCT(BlueprintType)
struct FLactoseTasksGetTasksResponse
{
    GENERATED_BODY()

    UPROPERTY(EditAnywhere, BlueprintReadWrite)
    TArray<FLactoseTasksGetTaskResponse> Tasks;

    static TArray<uint8> ToBytes(const FLactoseTasksGetTasksResponse& Object);

    TArray<uint8> ToBytes() const;

    static TOptional<FLactoseTasksGetTasksResponse> FromBytes(const TArray<uint8>& Bytes);
};

USTRUCT(BlueprintType)
struct FLactoseTasksCreateTaskRequest
{
    GENERATED_BODY()

    UPROPERTY(EditAnywhere, BlueprintReadWrite)
    FString Name;

    UPROPERTY(EditAnywhere, BlueprintReadWrite)
    TOptional<FString> Description;

    UPROPERTY(EditAnywhere, BlueprintReadWrite)
    double RequiredProgress = 0;

    UPROPERTY(EditAnywhere, BlueprintReadWrite)
    TArray<FLactoseTasksTriggerDto> Triggers;

    UPROPERTY(EditAnywhere, BlueprintReadWrite)
    TArray<FLactoseTasksItemRewardDto> Rewards;

    static TArray<uint8> ToBytes(const FLactoseTasksCreateTaskRequest& Object);

    TArray<uint8> ToBytes() const;

    static TOptional<FLactoseTasksCreateTaskRequest> FromBytes(const TArray<uint8>& Bytes);
};

USTRUCT(BlueprintType)
struct FLactoseTasksUpdateTaskRequest
{
    GENERATED_BODY()

    UPROPERTY(EditAnywhere, BlueprintReadWrite)
    FString Id;

    UPROPERTY(EditAnywhere, BlueprintReadWrite)
    TOptional<FString> Name;

    UPROPERTY(EditAnywhere, BlueprintReadWrite)
    TOptional<FString> Description;

    UPROPERTY(EditAnywhere, BlueprintReadWrite)
    TOptional<double> RequiredProgress;

    UPROPERTY(EditAnywhere, BlueprintReadWrite)
    TArray<FLactoseTasksTriggerDto> Triggers;

    UPROPERTY(EditAnywhere, BlueprintReadWrite)
    TArray<FLactoseTasksItemRewardDto> Rewards;

    static TArray<uint8> ToBytes(const FLactoseTasksUpdateTaskRequest& Object);

    TArray<uint8> ToBytes() const;

    static TOptional<FLactoseTasksUpdateTaskRequest> FromBytes(const TArray<uint8>& Bytes);
};

USTRUCT(BlueprintType)
struct FLactoseTasksDeleteTasksRequest
{
    GENERATED_BODY()

    UPROPERTY(EditAnywhere, BlueprintReadWrite)
    TArray<FString> TaskIds;

    static TArray<uint8> ToBytes(const FLactoseTasksDeleteTasksRequest& Object);

    TArray<uint8> ToBytes() const;

    static TOptional<FLactoseTasksDeleteTasksRequest> FromBytes(const TArray<uint8>& Bytes);
};

USTRUCT(BlueprintType)
struct FLactoseTasksDeleteTasksResponse
{
    GENERATED_BODY()

    UPROPERTY(EditAnywhere, BlueprintReadWrite)
    TArray<FString> DeletedTaskIds;

    static TArray<uint8> ToBytes(const FLactoseTasksDeleteTasksResponse& Object);

    TArray<uint8> ToBytes() const;

    static TOptional<FLactoseTasksDeleteTasksResponse> FromBytes(const TArray<uint8>& Bytes);
};

USTRUCT(BlueprintType)
struct FLactoseTasksTaskEvent
{
    GENERATED_BODY()

    UPROPERTY(EditAnywhere, BlueprintReadWrite)
    FString TaskId;

    static TArray<uint8> ToBytes(const FLactoseTasksTaskEvent& Object);

    TArray<uint8> ToBytes() const;

    static TOptional<FLactoseTasksTaskEvent> FromBytes(const TArray<uint8>& Bytes);
};
