//
// This file was generated by Catalyst's Unreal compiler at 02/05/2025 17:42:48.
// It is recommended not to modify this file. Modify the source spec file instead.
//

#include "LactoseTasksClient.h"

#include "CatalystSubsystem.h"

ULactoseTasksTasksClient::ULactoseTasksTasksClient()
{
    BaseUrl = TEXT("https://YouNeedToSet.Me");
}

TSharedRef<Lactose::Tasks::FQuery> ULactoseTasksTasksClient::Query(
    const FLactoseTasksQueryTasksRequest& Request,
    float Timeout)
{
    TArray<uint8> RequestBytes = Request.ToBytes();

    auto Operation = UCatalystSubsystem::Get().CreateOperation<Lactose::Tasks::FQuery>(
        BaseUrl + TEXT("/tasks") + TEXT("/query"),
        Catalyst::Verbs::POST,
        MoveTemp(RequestBytes),
        Timeout == Timeout::Default ? DefaultTimeout : Timeout
    );

    return Operation;
}

TSharedRef<Lactose::Tasks::FGet> ULactoseTasksTasksClient::Get(
    const FLactoseTasksGetTasksRequest& Request,
    float Timeout)
{
    TArray<uint8> RequestBytes = Request.ToBytes();

    auto Operation = UCatalystSubsystem::Get().CreateOperation<Lactose::Tasks::FGet>(
        BaseUrl + TEXT("/tasks") + TEXT("/get"),
        Catalyst::Verbs::POST,
        MoveTemp(RequestBytes),
        Timeout == Timeout::Default ? DefaultTimeout : Timeout
    );

    return Operation;
}

TSharedRef<Lactose::Tasks::FCreate> ULactoseTasksTasksClient::Create(
    const FLactoseTasksCreateTaskRequest& Request,
    float Timeout)
{
    TArray<uint8> RequestBytes = Request.ToBytes();

    auto Operation = UCatalystSubsystem::Get().CreateOperation<Lactose::Tasks::FCreate>(
        BaseUrl + TEXT("/tasks") + TEXT("/create"),
        Catalyst::Verbs::POST,
        MoveTemp(RequestBytes),
        Timeout == Timeout::Default ? DefaultTimeout : Timeout
    );

    return Operation;
}

TSharedRef<Lactose::Tasks::FDelete> ULactoseTasksTasksClient::Delete(
    const FLactoseTasksDeleteTasksRequest& Request,
    float Timeout)
{
    TArray<uint8> RequestBytes = Request.ToBytes();

    auto Operation = UCatalystSubsystem::Get().CreateOperation<Lactose::Tasks::FDelete>(
        BaseUrl + TEXT("/tasks") + TEXT("/delete"),
        Catalyst::Verbs::POST,
        MoveTemp(RequestBytes),
        Timeout == Timeout::Default ? DefaultTimeout : Timeout
    );

    return Operation;
}
