//
// This file was generated by Catalyst's Unreal compiler at 02/05/2025 17:42:48.
// It is recommended not to modify this file. Modify the source spec file instead.
//

#pragma once

#include "CatalystClient.h"
#include "CatalystOperation.h"
#include "LactoseTasks.h"
#include "Templates/SharedPointer.h"

#include "LactoseTasksClient.generated.h"


namespace Lactose::Tasks
{
    using FQuery = TCatalystOperation<FLactoseTasksQueryTasksResponse>;
    using FGet = TCatalystOperation<FLactoseTasksGetTasksResponse>;
    using FCreate = TCatalystOperation<FLactoseTasksGetTaskResponse>;
    using FDelete = TCatalystOperation<FLactoseTasksDeleteTasksResponse>;
}

UCLASS(Config=Catalyst, DefaultConfig)
class ULactoseTasksTasksClient : public UCatalystClient
{
    GENERATED_BODY()

public:
    ULactoseTasksTasksClient();

    TSharedRef<Lactose::Tasks::FQuery> Query(
        const FLactoseTasksQueryTasksRequest& Request,
        float Timeout = Timeout::Default);

    TSharedRef<Lactose::Tasks::FGet> Get(
        const FLactoseTasksGetTasksRequest& Request,
        float Timeout = Timeout::Default);

    TSharedRef<Lactose::Tasks::FCreate> Create(
        const FLactoseTasksCreateTaskRequest& Request,
        float Timeout = Timeout::Default);

    TSharedRef<Lactose::Tasks::FDelete> Delete(
        const FLactoseTasksDeleteTasksRequest& Request,
        float Timeout = Timeout::Default);
};
