//
// This file was generated by Catalyst's Unreal compiler at 02/05/2025 17:42:48.
// It is recommended not to modify this file. Modify the source spec file instead.
//

#pragma once

#include "LactoseTasksUserTasks.generated.h"

USTRUCT(BlueprintType)
struct FLactoseTasksQueryUserTasksRequest
{
    GENERATED_BODY()

    UPROPERTY(EditAnywhere, BlueprintReadWrite)
    FString UserId;

    static TArray<uint8> ToBytes(const FLactoseTasksQueryUserTasksRequest& Object);

    TArray<uint8> ToBytes() const;

    static TOptional<FLactoseTasksQueryUserTasksRequest> FromBytes(const TArray<uint8>& Bytes);
};

USTRUCT(BlueprintType)
struct FLactoseTasksQueryUserTasksResponse
{
    GENERATED_BODY()

    UPROPERTY(EditAnywhere, BlueprintReadWrite)
    TArray<FString> UserTaskIds;

    static TArray<uint8> ToBytes(const FLactoseTasksQueryUserTasksResponse& Object);

    TArray<uint8> ToBytes() const;

    static TOptional<FLactoseTasksQueryUserTasksResponse> FromBytes(const TArray<uint8>& Bytes);
};

USTRUCT(BlueprintType)
struct FLactoseTasksGetUserTasksRequest
{
    GENERATED_BODY()

    UPROPERTY(EditAnywhere, BlueprintReadWrite)
    TArray<FString> UserTaskIds;

    static TArray<uint8> ToBytes(const FLactoseTasksGetUserTasksRequest& Object);

    TArray<uint8> ToBytes() const;

    static TOptional<FLactoseTasksGetUserTasksRequest> FromBytes(const TArray<uint8>& Bytes);
};

USTRUCT(BlueprintType)
struct FLactoseTasksGetUserTasksFromTaskIdRequest
{
    GENERATED_BODY()

    UPROPERTY(EditAnywhere, BlueprintReadWrite)
    FString UserId;

    UPROPERTY(EditAnywhere, BlueprintReadWrite)
    TArray<FString> TaskIds;

    static TArray<uint8> ToBytes(const FLactoseTasksGetUserTasksFromTaskIdRequest& Object);

    TArray<uint8> ToBytes() const;

    static TOptional<FLactoseTasksGetUserTasksFromTaskIdRequest> FromBytes(const TArray<uint8>& Bytes);
};

USTRUCT(BlueprintType)
struct FLactoseTasksUserTaskDto
{
    GENERATED_BODY()

    UPROPERTY(EditAnywhere, BlueprintReadWrite)
    FString Id;

    UPROPERTY(EditAnywhere, BlueprintReadWrite)
    FString UserId;

    UPROPERTY(EditAnywhere, BlueprintReadWrite)
    FString TaskId;

    UPROPERTY(EditAnywhere, BlueprintReadWrite)
    double Progress = 0;

    UPROPERTY(EditAnywhere, BlueprintReadWrite)
    bool Completed = false;

    static TArray<uint8> ToBytes(const FLactoseTasksUserTaskDto& Object);

    TArray<uint8> ToBytes() const;

    static TOptional<FLactoseTasksUserTaskDto> FromBytes(const TArray<uint8>& Bytes);
};

USTRUCT(BlueprintType)
struct FLactoseTasksGetUserTasksResponse
{
    GENERATED_BODY()

    UPROPERTY(EditAnywhere, BlueprintReadWrite)
    TArray<FLactoseTasksUserTaskDto> UserTasks;

    static TArray<uint8> ToBytes(const FLactoseTasksGetUserTasksResponse& Object);

    TArray<uint8> ToBytes() const;

    static TOptional<FLactoseTasksGetUserTasksResponse> FromBytes(const TArray<uint8>& Bytes);
};


USTRUCT(BlueprintType)
struct FLactoseTasksUserTaskUpdatedEvent
{
    GENERATED_BODY()
    
    UPROPERTY(EditAnywhere, BlueprintReadWrite)
    FString UserId;

    UPROPERTY(EditAnywhere, BlueprintReadWrite)
    FString TaskId;

    UPROPERTY(EditAnywhere, BlueprintReadWrite)
    FString UserTaskId;

    UPROPERTY(EditAnywhere, BlueprintReadWrite)
    double PreviousProgress = 0;

    static TArray<uint8> ToBytes(const FLactoseTasksUserTaskUpdatedEvent& Object);

    TArray<uint8> ToBytes() const;

    static TOptional<FLactoseTasksUserTaskUpdatedEvent> FromBytes(const TArray<uint8>& Bytes);
};

