//
// This file was generated by Catalyst's Unreal compiler at 02/05/2025 17:42:48.
// It is recommended not to modify this file. Modify the source spec file instead.
//

#include "LactoseTasksUserTasks.h"

#include "CatalystJson.h"
#include "Templates/SharedPointer.h"


TArray<uint8> FLactoseTasksQueryUserTasksRequest::ToBytes(const FLactoseTasksQueryUserTasksRequest& Object)
{
    TSharedPtr<FJsonObject> JsonObject = Catalyst::Json::StructToJsonObject(Object);
    return JsonObject ? Catalyst::Json::JsonObjectToBytes(JsonObject.ToSharedRef()) : TArray<uint8>();
}

TArray<uint8> FLactoseTasksQueryUserTasksRequest::ToBytes() const
{
    return ToBytes(*this);
}

TOptional<FLactoseTasksQueryUserTasksRequest> FLactoseTasksQueryUserTasksRequest::FromBytes(const TArray<uint8>& Bytes)
{
    TSharedPtr<FJsonObject> JsonObject = Catalyst::Json::BytesToJsonObject(Bytes);
    return JsonObject ? Catalyst::Json::JsonObjectToStruct<FLactoseTasksQueryUserTasksRequest>(JsonObject.ToSharedRef()) : TOptional<FLactoseTasksQueryUserTasksRequest>();
}

TArray<uint8> FLactoseTasksQueryUserTasksResponse::ToBytes(const FLactoseTasksQueryUserTasksResponse& Object)
{
    TSharedPtr<FJsonObject> JsonObject = Catalyst::Json::StructToJsonObject(Object);
    return JsonObject ? Catalyst::Json::JsonObjectToBytes(JsonObject.ToSharedRef()) : TArray<uint8>();
}

TArray<uint8> FLactoseTasksQueryUserTasksResponse::ToBytes() const
{
    return ToBytes(*this);
}

TOptional<FLactoseTasksQueryUserTasksResponse> FLactoseTasksQueryUserTasksResponse::FromBytes(const TArray<uint8>& Bytes)
{
    TSharedPtr<FJsonObject> JsonObject = Catalyst::Json::BytesToJsonObject(Bytes);
    return JsonObject ? Catalyst::Json::JsonObjectToStruct<FLactoseTasksQueryUserTasksResponse>(JsonObject.ToSharedRef()) : TOptional<FLactoseTasksQueryUserTasksResponse>();
}

TArray<uint8> FLactoseTasksGetUserTasksRequest::ToBytes(const FLactoseTasksGetUserTasksRequest& Object)
{
    TSharedPtr<FJsonObject> JsonObject = Catalyst::Json::StructToJsonObject(Object);
    return JsonObject ? Catalyst::Json::JsonObjectToBytes(JsonObject.ToSharedRef()) : TArray<uint8>();
}

TArray<uint8> FLactoseTasksGetUserTasksRequest::ToBytes() const
{
    return ToBytes(*this);
}

TOptional<FLactoseTasksGetUserTasksRequest> FLactoseTasksGetUserTasksRequest::FromBytes(const TArray<uint8>& Bytes)
{
    TSharedPtr<FJsonObject> JsonObject = Catalyst::Json::BytesToJsonObject(Bytes);
    return JsonObject ? Catalyst::Json::JsonObjectToStruct<FLactoseTasksGetUserTasksRequest>(JsonObject.ToSharedRef()) : TOptional<FLactoseTasksGetUserTasksRequest>();
}

TArray<uint8> FLactoseTasksGetUserTasksFromTaskIdRequest::ToBytes(const FLactoseTasksGetUserTasksFromTaskIdRequest& Object)
{
    TSharedPtr<FJsonObject> JsonObject = Catalyst::Json::StructToJsonObject(Object);
    return JsonObject ? Catalyst::Json::JsonObjectToBytes(JsonObject.ToSharedRef()) : TArray<uint8>();
}

TArray<uint8> FLactoseTasksGetUserTasksFromTaskIdRequest::ToBytes() const
{
    return ToBytes(*this);
}

TOptional<FLactoseTasksGetUserTasksFromTaskIdRequest> FLactoseTasksGetUserTasksFromTaskIdRequest::FromBytes(const TArray<uint8>& Bytes)
{
    TSharedPtr<FJsonObject> JsonObject = Catalyst::Json::BytesToJsonObject(Bytes);
    return JsonObject ? Catalyst::Json::JsonObjectToStruct<FLactoseTasksGetUserTasksFromTaskIdRequest>(JsonObject.ToSharedRef()) : TOptional<FLactoseTasksGetUserTasksFromTaskIdRequest>();
}

TArray<uint8> FLactoseTasksUserTaskDto::ToBytes(const FLactoseTasksUserTaskDto& Object)
{
    TSharedPtr<FJsonObject> JsonObject = Catalyst::Json::StructToJsonObject(Object);
    return JsonObject ? Catalyst::Json::JsonObjectToBytes(JsonObject.ToSharedRef()) : TArray<uint8>();
}

TArray<uint8> FLactoseTasksUserTaskDto::ToBytes() const
{
    return ToBytes(*this);
}

TOptional<FLactoseTasksUserTaskDto> FLactoseTasksUserTaskDto::FromBytes(const TArray<uint8>& Bytes)
{
    TSharedPtr<FJsonObject> JsonObject = Catalyst::Json::BytesToJsonObject(Bytes);
    return JsonObject ? Catalyst::Json::JsonObjectToStruct<FLactoseTasksUserTaskDto>(JsonObject.ToSharedRef()) : TOptional<FLactoseTasksUserTaskDto>();
}

TArray<uint8> FLactoseTasksGetUserTasksResponse::ToBytes(const FLactoseTasksGetUserTasksResponse& Object)
{
    TSharedPtr<FJsonObject> JsonObject = Catalyst::Json::StructToJsonObject(Object);
    return JsonObject ? Catalyst::Json::JsonObjectToBytes(JsonObject.ToSharedRef()) : TArray<uint8>();
}

TArray<uint8> FLactoseTasksGetUserTasksResponse::ToBytes() const
{
    return ToBytes(*this);
}

TOptional<FLactoseTasksGetUserTasksResponse> FLactoseTasksGetUserTasksResponse::FromBytes(const TArray<uint8>& Bytes)
{
    TSharedPtr<FJsonObject> JsonObject = Catalyst::Json::BytesToJsonObject(Bytes);
    return JsonObject ? Catalyst::Json::JsonObjectToStruct<FLactoseTasksGetUserTasksResponse>(JsonObject.ToSharedRef()) : TOptional<FLactoseTasksGetUserTasksResponse>();
}

TArray<uint8> FLactoseTasksUserTaskUpdatedEvent::ToBytes(const FLactoseTasksUserTaskUpdatedEvent& Object)
{
    TSharedPtr<FJsonObject> JsonObject = Catalyst::Json::StructToJsonObject(Object);
    return JsonObject ? Catalyst::Json::JsonObjectToBytes(JsonObject.ToSharedRef()) : TArray<uint8>();
}

TArray<uint8> FLactoseTasksUserTaskUpdatedEvent::ToBytes() const
{
    return ToBytes(*this);
}

TOptional<FLactoseTasksUserTaskUpdatedEvent> FLactoseTasksUserTaskUpdatedEvent::FromBytes(const TArray<uint8>& Bytes)
{
    TSharedPtr<FJsonObject> JsonObject = Catalyst::Json::BytesToJsonObject(Bytes);
    return JsonObject ? Catalyst::Json::JsonObjectToStruct<FLactoseTasksUserTaskUpdatedEvent>(JsonObject.ToSharedRef()) : TOptional<FLactoseTasksUserTaskUpdatedEvent>();
}
